/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ece.nitdgp.ac.in)
#  Generated on:      Thu Mar 26 19:34:11 2026
#  Design:            dvfs_tunable_multiplier
#  Command:           saveNetlist -includePowerGround ./ClockTreeReports_dvfs/top_chip_wrapper_postCTS_withPG.v
###############################################################
*/
module buffd1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module bufbd4 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module dl01d1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module dl02d2 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module inv0d0 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nd12d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nd12d2 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nd02d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module inv0d1 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module aor21d2 (
	A, 
	B1, 
	B2, 
	Z, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module or02d0 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module nd03d2 (
	A1, 
	A2, 
	A3, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module dfnrq1 (
	CP, 
	D, 
	Q, 
	VSS, 
	VDD);
   input CP;
   input D;
   output Q;
   inout VSS;
   inout VDD;
endmodule

module dfcrq1 (
	CDN, 
	CP, 
	D, 
	Q, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   inout VSS;
   inout VDD;
endmodule

module aor222d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	C1, 
	C2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   input C1;
   input C2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module aor22d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module oai31d1 (
	A, 
	B1, 
	B2, 
	B3, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   input B3;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module aon211d1 (
	A, 
	B, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module oaim22d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module oai22d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module oaim21d1 (
	A, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nr02d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module oan211d1 (
	A, 
	B, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module aoi221d1 (
	A, 
	B1, 
	B2, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module an02d1 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module mx02d1 (
	I0, 
	I1, 
	S, 
	Z, 
	VSS, 
	VDD);
   input I0;
   input I1;
   input S;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module oai21d1 (
	A, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module cg01d0 (
	A, 
	B, 
	CI, 
	CO, 
	VSS, 
	VDD);
   input A;
   input B;
   input CI;
   output CO;
   inout VSS;
   inout VDD;
endmodule

module nr03d1 (
	A1, 
	A2, 
	A3, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module aoim21d1 (
	A, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module aoi22d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module ora21d1 (
	A, 
	B1, 
	B2, 
	Z, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module inv0d2 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module ad01d1 (
	A, 
	B, 
	CI, 
	CO, 
	S, 
	VSS, 
	VDD);
   input A;
   input B;
   input CI;
   output CO;
   output S;
   inout VSS;
   inout VDD;
endmodule

module nd03d1 (
	A1, 
	A2, 
	A3, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module or02d1 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module dfcrb1 (
	CDN, 
	CP, 
	D, 
	Q, 
	QN, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   output QN;
   inout VSS;
   inout VDD;
endmodule

module dfcrb4 (
	CDN, 
	CP, 
	D, 
	Q, 
	QN, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   output QN;
   inout VSS;
   inout VDD;
endmodule

module dfcrb2 (
	CDN, 
	CP, 
	D, 
	Q, 
	QN, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   output QN;
   inout VSS;
   inout VDD;
endmodule

// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 22 2026 20:31:07 IST (Mar 22 2026 15:01:07 UTC)
// Verification Directory fv/dvfs_tunable_multiplier 
module dvfs_tunable_multiplier (
	clk_in, 
	rst, 
	start, 
	a, 
	b, 
	precision, 
	dvfs_v_state, 
	result, 
	done);
   input clk_in;
   input rst;
   input start;
   input [7:0] a;
   input [7:0] b;
   input [3:0] precision;
   input [1:0] dvfs_v_state;
   output [15:0] result;
   output done;

   // Internal wires
   wire FE_PHN23_n_79;
   wire FE_PHN22_n_82;
   wire FE_PHN21_n_84;
   wire FE_PHN20_n_85;
   wire FE_PHN19_n_83;
   wire FE_PHN18_div_counter_0;
   wire FE_PHN17_n_82;
   wire FE_PHN16_n_83;
   wire FE_PHN15_n_84;
   wire FE_PHN14_n_85;
   wire FE_PHN13_n_79;
   wire FE_PHN12_n_80;
   wire FE_PHN11_n_90;
   wire FE_PHN10_n_72;
   wire FE_PHN9_n_38;
   wire FE_PHN8_n_40;
   wire FE_PHN7_n_37;
   wire FE_PHN6_n_36;
   wire FE_PHN5_n_39;
   wire FE_PHN4_n_33;
   wire FE_PHN3_n_34;
   wire FE_PHN2_n_35;
   wire FE_PHN1_n_1;
   wire FE_RN_11_0;
   wire FE_RN_10_0;
   wire FE_RN_9_0;
   wire FE_RN_8_0;
   wire FE_RN_7_0;
   wire FE_RN_6_0;
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_RN_3_0;
   wire FE_RN_2_0;
   wire FE_RN_1_0;
   wire FE_RN_0_0;
   wire VSSO_CORE;
   wire VSS_CORE;
   wire VDDO_CORE;
   wire VDD_CORE;
   wire [7:0] b_reg;
   wire [3:0] cycle_count;
   wire [2:0] div_counter;
   wire [15:0] shifted_a;
   wire add_73_46_n_315;
   wire add_73_46_n_317;
   wire add_73_46_n_322;
   wire add_73_46_n_327;
   wire add_73_46_n_332;
   wire add_73_46_n_340;
   wire add_73_46_n_345;
   wire add_73_46_n_352;
   wire add_73_46_n_356;
   wire add_73_46_n_361;
   wire add_73_46_n_362;
   wire add_73_46_n_368;
   wire add_73_46_n_373;
   wire add_73_46_n_377;
   wire add_73_46_n_384;
   wire add_73_46_n_389;
   wire add_73_46_n_390;
   wire add_73_46_n_391;
   wire add_73_46_n_392;
   wire add_73_46_n_393;
   wire add_73_46_n_394;
   wire add_73_46_n_411;
   wire add_73_46_n_412;
   wire add_73_46_n_413;
   wire add_73_46_n_414;
   wire add_73_46_n_415;
   wire add_73_46_n_416;
   wire add_73_46_n_417;
   wire add_73_46_n_428;
   wire add_73_46_n_429;
   wire add_73_46_n_430;
   wire add_73_46_n_431;
   wire add_73_46_n_433;
   wire add_73_46_n_434;
   wire add_73_46_n_435;
   wire add_73_46_n_436;
   wire add_73_46_n_437;
   wire add_73_46_n_438;
   wire add_73_46_n_439;
   wire add_73_46_n_440;
   wire add_73_46_n_441;
   wire add_73_46_n_445;
   wire add_73_46_n_446;
   wire add_73_46_n_447;
   wire add_73_46_n_449;
   wire add_73_46_n_450;
   wire add_73_46_n_451;
   wire add_73_46_n_452;
   wire add_73_46_n_453;
   wire add_73_46_n_454;
   wire add_73_46_n_455;
   wire add_73_46_n_456;
   wire add_73_46_n_457;
   wire add_73_46_n_458;
   wire add_73_46_n_496;
   wire add_73_46_n_512;
   wire add_73_46_n_513;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_132;
   wire n_133;
   wire n_134;
   wire state;

   // Module instantiations
   buffd1 FE_PHC23_n_79 (
	.I(FE_PHN13_n_79),
	.Z(FE_PHN23_n_79), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_PHC22_n_82 (
	.I(FE_PHN17_n_82),
	.Z(FE_PHN22_n_82), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_PHC21_n_84 (
	.I(FE_PHN15_n_84),
	.Z(FE_PHN21_n_84), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_PHC20_n_85 (
	.I(FE_PHN14_n_85),
	.Z(FE_PHN20_n_85), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_PHC19_n_83 (
	.I(FE_PHN16_n_83),
	.Z(FE_PHN19_n_83), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_PHC18_div_counter_0 (
	.I(div_counter[0]),
	.Z(FE_PHN18_div_counter_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   bufbd4 FE_PHC17_n_82 (
	.I(n_82),
	.Z(FE_PHN17_n_82), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   bufbd4 FE_PHC16_n_83 (
	.I(n_83),
	.Z(FE_PHN16_n_83), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   bufbd4 FE_PHC15_n_84 (
	.I(n_84),
	.Z(FE_PHN15_n_84), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   bufbd4 FE_PHC14_n_85 (
	.I(n_85),
	.Z(FE_PHN14_n_85), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   bufbd4 FE_PHC13_n_79 (
	.I(n_79),
	.Z(FE_PHN13_n_79), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   bufbd4 FE_PHC12_n_80 (
	.I(n_80),
	.Z(FE_PHN12_n_80), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   bufbd4 FE_PHC11_n_90 (
	.I(n_90),
	.Z(FE_PHN11_n_90), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC10_n_72 (
	.I(n_72),
	.Z(FE_PHN10_n_72), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC9_n_38 (
	.I(n_38),
	.Z(FE_PHN9_n_38), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC8_n_40 (
	.I(n_40),
	.Z(FE_PHN8_n_40), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC7_n_37 (
	.I(n_37),
	.Z(FE_PHN7_n_37), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC6_n_36 (
	.I(n_36),
	.Z(FE_PHN6_n_36), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC5_n_39 (
	.I(n_39),
	.Z(FE_PHN5_n_39), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC4_n_33 (
	.I(n_33),
	.Z(FE_PHN4_n_33), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC3_n_34 (
	.I(n_34),
	.Z(FE_PHN3_n_34), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC2_n_35 (
	.I(n_35),
	.Z(FE_PHN2_n_35), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl02d2 FE_PHC1_n_1 (
	.I(n_1),
	.Z(FE_PHN1_n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 FE_RC_17_0 (
	.I(add_73_46_n_429),
	.ZN(FE_RN_9_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 FE_RC_16_0 (
	.A1(FE_RN_9_0),
	.A2(add_73_46_n_352),
	.ZN(FE_RN_10_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 FE_RC_15_0 (
	.I(add_73_46_n_449),
	.ZN(FE_RN_11_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d2 FE_RC_14_0 (
	.A1(FE_RN_11_0),
	.A2(FE_RN_10_0),
	.ZN(add_73_46_n_512), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 FE_RC_13_0 (
	.A1(add_73_46_n_513),
	.A2(add_73_46_n_458),
	.ZN(FE_RN_7_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d1 FE_RC_12_0 (
	.I(add_73_46_n_436),
	.ZN(FE_RN_8_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d2 FE_RC_11_0 (
	.A1(FE_RN_8_0),
	.A2(FE_RN_7_0),
	.ZN(n_134), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 FE_RC_10_0 (
	.I(add_73_46_n_451),
	.ZN(FE_RN_4_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 FE_RC_9_0 (
	.A1(FE_RN_4_0),
	.A2(add_73_46_n_332),
	.ZN(FE_RN_5_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 FE_RC_8_0 (
	.I(add_73_46_n_446),
	.ZN(FE_RN_6_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d2 FE_RC_7_0 (
	.A1(FE_RN_6_0),
	.A2(FE_RN_5_0),
	.ZN(add_73_46_n_327), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 FE_RC_6_0 (
	.I(add_73_46_n_455),
	.ZN(FE_RN_3_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor21d2 FE_RC_5_0 (
	.A(FE_RN_3_0),
	.B1(n_132),
	.B2(add_73_46_n_456),
	.Z(add_73_46_n_332), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 FE_RC_4_0 (
	.A1(add_73_46_n_322),
	.A2(add_73_46_n_453),
	.ZN(FE_RN_1_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 FE_RC_3_0 (
	.I(add_73_46_n_437),
	.ZN(FE_RN_2_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 FE_RC_2_0 (
	.A1(FE_RN_2_0),
	.A2(FE_RN_1_0),
	.ZN(add_73_46_n_317), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d0 FE_RC_1_0 (
	.A1(add_73_46_n_440),
	.A2(add_73_46_n_457),
	.Z(FE_RN_0_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd03d2 FE_RC_0_0 (
	.A1(add_73_46_n_454),
	.A2(FE_RN_0_0),
	.A3(add_73_46_n_361),
	.ZN(n_133), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d1 FE_OFC0_add_73_46_n_384 (
	.I(add_73_46_n_384),
	.ZN(add_73_46_n_458), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \b_reg_reg[0]  (
	.CP(clk_in),
	.D(FE_PHN5_n_39),
	.Q(b_reg[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \b_reg_reg[1]  (
	.CP(clk_in),
	.D(FE_PHN8_n_40),
	.Q(b_reg[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \b_reg_reg[2]  (
	.CP(clk_in),
	.D(FE_PHN9_n_38),
	.Q(b_reg[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \b_reg_reg[3]  (
	.CP(clk_in),
	.D(FE_PHN2_n_35),
	.Q(b_reg[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \b_reg_reg[4]  (
	.CP(clk_in),
	.D(FE_PHN6_n_36),
	.Q(b_reg[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \b_reg_reg[5]  (
	.CP(clk_in),
	.D(FE_PHN7_n_37),
	.Q(b_reg[5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \b_reg_reg[6]  (
	.CP(clk_in),
	.D(FE_PHN3_n_34),
	.Q(b_reg[6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \b_reg_reg[7]  (
	.CP(clk_in),
	.D(FE_PHN4_n_33),
	.Q(b_reg[7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \cycle_count_reg[1]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_58),
	.Q(cycle_count[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \div_counter_reg[1]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_19),
	.Q(div_counter[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \div_counter_reg[2]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_25),
	.Q(div_counter[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 done_reg (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_48),
	.Q(done), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[0]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_71),
	.Q(result[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[1]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_70),
	.Q(result[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[2]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_69),
	.Q(result[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[3]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_77),
	.Q(result[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[4]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_67),
	.Q(result[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[5]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_66),
	.Q(result[5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[6]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_65),
	.Q(result[6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[7]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_64),
	.Q(result[7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[8]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_63),
	.Q(result[8]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[9]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_62),
	.Q(result[9]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[10]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_61),
	.Q(result[10]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[11]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_60),
	.Q(result[11]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[12]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_86),
	.Q(result[12]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[13]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_78),
	.Q(result[13]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \result_reg[14]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_81),
	.Q(result[14]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[0]  (
	.CP(clk_in),
	.D(n_88),
	.Q(shifted_a[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[1]  (
	.CP(clk_in),
	.D(n_89),
	.Q(shifted_a[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[2]  (
	.CP(clk_in),
	.D(n_68),
	.Q(shifted_a[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[3]  (
	.CP(clk_in),
	.D(n_76),
	.Q(shifted_a[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[4]  (
	.CP(clk_in),
	.D(n_75),
	.Q(shifted_a[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[5]  (
	.CP(clk_in),
	.D(n_74),
	.Q(shifted_a[5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[6]  (
	.CP(clk_in),
	.D(n_73),
	.Q(shifted_a[6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[7]  (
	.CP(clk_in),
	.D(FE_PHN20_n_85),
	.Q(shifted_a[7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[8]  (
	.CP(clk_in),
	.D(FE_PHN21_n_84),
	.Q(shifted_a[8]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[9]  (
	.CP(clk_in),
	.D(FE_PHN19_n_83),
	.Q(shifted_a[9]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[10]  (
	.CP(clk_in),
	.D(FE_PHN22_n_82),
	.Q(shifted_a[10]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[11]  (
	.CP(clk_in),
	.D(FE_PHN11_n_90),
	.Q(shifted_a[11]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[12]  (
	.CP(clk_in),
	.D(FE_PHN12_n_80),
	.Q(shifted_a[12]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[13]  (
	.CP(clk_in),
	.D(FE_PHN23_n_79),
	.Q(shifted_a[13]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfnrq1 \shifted_a_reg[14]  (
	.CP(clk_in),
	.D(FE_PHN10_n_72),
	.Q(shifted_a[14]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor222d1 g2956__2398 (
	.A1(n_53),
	.A2(shifted_a[11]),
	.B1(n_45),
	.B2(shifted_a[12]),
	.C1(n_32),
	.C2(a[4]),
	.Z(n_90), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2957__5107 (
	.A1(n_53),
	.A2(shifted_a[1]),
	.B1(n_45),
	.B2(shifted_a[2]),
	.Z(n_89), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2958__6260 (
	.A1(n_53),
	.A2(shifted_a[0]),
	.B1(n_45),
	.B2(shifted_a[1]),
	.Z(n_88), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2959__4319 (
	.A1(n_52),
	.A2(result[15]),
	.B1(n_106),
	.B2(n_49),
	.Z(n_87), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2960__8428 (
	.A1(n_52),
	.A2(result[12]),
	.B1(n_103),
	.B2(n_49),
	.Z(n_86), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor222d1 g2961__5526 (
	.A1(n_53),
	.A2(shifted_a[7]),
	.B1(n_45),
	.B2(shifted_a[8]),
	.C1(n_32),
	.C2(a[0]),
	.Z(n_85), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor222d1 g2962__6783 (
	.A1(n_53),
	.A2(shifted_a[8]),
	.B1(n_45),
	.B2(shifted_a[9]),
	.C1(n_32),
	.C2(a[1]),
	.Z(n_84), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor222d1 g2963__3680 (
	.A1(n_53),
	.A2(shifted_a[9]),
	.B1(n_45),
	.B2(shifted_a[10]),
	.C1(n_32),
	.C2(a[2]),
	.Z(n_83), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor222d1 g2964__1617 (
	.A1(n_53),
	.A2(shifted_a[10]),
	.B1(n_45),
	.B2(shifted_a[11]),
	.C1(n_32),
	.C2(a[3]),
	.Z(n_82), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2965__2802 (
	.A1(n_52),
	.A2(result[14]),
	.B1(n_105),
	.B2(n_49),
	.Z(n_81), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor222d1 g2966__1705 (
	.A1(n_53),
	.A2(shifted_a[12]),
	.B1(n_45),
	.B2(shifted_a[13]),
	.C1(n_32),
	.C2(a[5]),
	.Z(n_80), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor222d1 g2967__5122 (
	.A1(n_53),
	.A2(shifted_a[13]),
	.B1(n_45),
	.B2(shifted_a[14]),
	.C1(n_32),
	.C2(a[6]),
	.Z(n_79), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2968__8246 (
	.A1(n_52),
	.A2(result[13]),
	.B1(n_104),
	.B2(n_49),
	.Z(n_78), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2974__7098 (
	.A1(n_52),
	.A2(result[3]),
	.B1(n_49),
	.B2(n_94),
	.Z(n_77), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2975__6131 (
	.A1(n_53),
	.A2(shifted_a[3]),
	.B1(n_45),
	.B2(shifted_a[4]),
	.Z(n_76), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2976__1881 (
	.A1(n_53),
	.A2(shifted_a[4]),
	.B1(n_45),
	.B2(shifted_a[5]),
	.Z(n_75), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2977__5115 (
	.A1(n_53),
	.A2(shifted_a[5]),
	.B1(n_45),
	.B2(shifted_a[6]),
	.Z(n_74), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2978__7482 (
	.A1(n_53),
	.A2(shifted_a[6]),
	.B1(n_45),
	.B2(shifted_a[7]),
	.Z(n_73), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2979__4733 (
	.A1(n_53),
	.A2(shifted_a[14]),
	.B1(n_32),
	.B2(a[7]),
	.Z(n_72), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2980__6161 (
	.A1(n_52),
	.A2(result[0]),
	.B1(n_49),
	.B2(n_91),
	.Z(n_71), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2981__9315 (
	.A1(n_52),
	.A2(result[1]),
	.B1(n_49),
	.B2(n_92),
	.Z(n_70), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2982__9945 (
	.A1(n_52),
	.A2(result[2]),
	.B1(n_49),
	.B2(n_93),
	.Z(n_69), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2983__2883 (
	.A1(n_53),
	.A2(shifted_a[2]),
	.B1(n_45),
	.B2(shifted_a[3]),
	.Z(n_68), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2984__2346 (
	.A1(n_52),
	.A2(result[4]),
	.B1(n_49),
	.B2(n_95),
	.Z(n_67), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2985__1666 (
	.A1(n_52),
	.A2(result[5]),
	.B1(n_49),
	.B2(n_96),
	.Z(n_66), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2986__7410 (
	.A1(n_52),
	.A2(result[6]),
	.B1(n_49),
	.B2(n_97),
	.Z(n_65), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2987__6417 (
	.A1(n_52),
	.A2(result[7]),
	.B1(n_98),
	.B2(n_49),
	.Z(n_64), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2988__5477 (
	.A1(n_52),
	.A2(result[8]),
	.B1(n_99),
	.B2(n_49),
	.Z(n_63), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2989__2398 (
	.A1(n_52),
	.A2(result[9]),
	.B1(n_100),
	.B2(n_49),
	.Z(n_62), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2990__5107 (
	.A1(n_52),
	.A2(result[10]),
	.B1(n_101),
	.B2(n_49),
	.Z(n_61), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 g2991__6260 (
	.A1(n_52),
	.A2(result[11]),
	.B1(n_102),
	.B2(n_49),
	.Z(n_60), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai31d1 g2992__4319 (
	.A(n_54),
	.B1(n_42),
	.B2(n_6),
	.B3(n_12),
	.ZN(n_59), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aon211d1 g2993__8428 (
	.A(n_51),
	.B(n_42),
	.C1(n_10),
	.C2(n_0),
	.ZN(n_58), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 g2994__5526 (
	.A1(n_50),
	.A2(state),
	.B1(n_50),
	.B2(state),
	.ZN(n_57), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai22d1 g2995__6783 (
	.A1(n_42),
	.A2(n_20),
	.B1(n_47),
	.B2(n_6),
	.ZN(n_56), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai22d1 g2996__3680 (
	.A1(n_47),
	.A2(n_3),
	.B1(n_42),
	.B2(cycle_count[0]),
	.ZN(n_55), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g2997__1617 (
	.A1(n_46),
	.A2(cycle_count[3]),
	.ZN(n_54), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g2999__2802 (
	.A1(n_46),
	.A2(cycle_count[1]),
	.ZN(n_51), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3000__1705 (
	.A1(n_47),
	.A2(n_1),
	.ZN(n_53), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim21d1 g3001__5122 (
	.A(n_47),
	.B1(n_28),
	.B2(state),
	.ZN(n_52), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3002__8246 (
	.A1(n_29),
	.A2(n_43),
	.ZN(n_50), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3003__7098 (
	.A1(n_28),
	.A2(n_42),
	.ZN(n_49), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g3004 (
	.I(n_44),
	.ZN(n_48), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g3005 (
	.I(n_47),
	.ZN(n_46), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oan211d1 g3006__6131 (
	.A(n_43),
	.B(done),
	.C1(n_27),
	.C2(state),
	.ZN(n_44), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi221d1 g3007__1881 (
	.A(n_27),
	.B1(n_2),
	.B2(n_8),
	.C1(state),
	.C2(n_41),
	.ZN(n_47), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3008__5115 (
	.A1(rst),
	.A2(n_42),
	.ZN(n_45), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g3017__7482 (
	.A1(n_41),
	.A2(n_30),
	.Z(n_43), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g3018__4733 (
	.A1(n_41),
	.A2(n_30),
	.ZN(n_42), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g3019__6161 (
	.I0(b_reg[1]),
	.I1(b[1]),
	.S(n_32),
	.Z(n_40), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g3020__9315 (
	.I0(b_reg[0]),
	.I1(b[0]),
	.S(n_32),
	.Z(n_39), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g3021__9945 (
	.I0(b_reg[2]),
	.I1(b[2]),
	.S(n_32),
	.Z(n_38), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai21d1 g3022__2883 (
	.A(n_7),
	.B1(n_31),
	.B2(precision[3]),
	.ZN(n_41), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g3023__2346 (
	.I0(b_reg[5]),
	.I1(b[5]),
	.S(n_32),
	.Z(n_37), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g3024__1666 (
	.I0(b_reg[4]),
	.I1(b[4]),
	.S(n_32),
	.Z(n_36), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g3025__7410 (
	.I0(b_reg[3]),
	.I1(b[3]),
	.S(n_32),
	.Z(n_35), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g3026__6417 (
	.I0(b_reg[6]),
	.I1(b[6]),
	.S(n_32),
	.Z(n_34), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g3027__5477 (
	.I0(b_reg[7]),
	.I1(b[7]),
	.S(n_32),
	.Z(n_33), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 g3028__2398 (
	.A1(n_29),
	.A2(n_1),
	.Z(n_32), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   cg01d0 g3029__5107 (
	.A(n_6),
	.B(precision[2]),
	.CI(n_26),
	.CO(n_31), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3031__6260 (
	.A1(n_2),
	.A2(n_27),
	.ZN(n_30), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr03d1 g3032__4319 (
	.A1(n_8),
	.A2(state),
	.A3(n_27),
	.ZN(n_29), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3033__8428 (
	.A1(n_23),
	.A2(n_22),
	.ZN(n_28), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oan211d1 g3034__5526 (
	.A(n_24),
	.B(dvfs_v_state[1]),
	.C1(n_4),
	.C2(dvfs_v_state[0]),
	.ZN(n_27), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oan211d1 g3035__6783 (
	.A(n_11),
	.B(n_21),
	.C1(cycle_count[1]),
	.C2(n_5),
	.ZN(n_26), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 g3036__3680 (
	.A1(n_9),
	.A2(div_counter[2]),
	.B1(n_9),
	.B2(div_counter[2]),
	.ZN(n_25), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim21d1 g3037__1617 (
	.A(n_9),
	.B1(div_counter[2]),
	.B2(dvfs_v_state[0]),
	.ZN(n_24), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai22d1 g3039__2802 (
	.A1(n_17),
	.A2(n_0),
	.B1(n_18),
	.B2(n_10),
	.ZN(n_23), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai22d1 g3040__1705 (
	.A1(n_15),
	.A2(n_14),
	.B1(n_16),
	.B2(n_12),
	.ZN(n_22), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai21d1 g3041__5122 (
	.A(precision[0]),
	.B1(n_13),
	.B2(precision[1]),
	.ZN(n_21), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3042__8246 (
	.A1(n_11),
	.A2(n_6),
	.B1(n_12),
	.B2(cycle_count[2]),
	.ZN(n_20), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ora21d1 g3043__7098 (
	.A(n_9),
	.B1(n_4),
	.B2(div_counter[1]),
	.Z(n_19), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3044__6131 (
	.A1(n_6),
	.A2(b_reg[5]),
	.B1(cycle_count[2]),
	.B2(b_reg[1]),
	.ZN(n_18), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3045__1881 (
	.A1(n_6),
	.A2(b_reg[6]),
	.B1(cycle_count[2]),
	.B2(b_reg[2]),
	.ZN(n_17), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3046__5115 (
	.A1(n_6),
	.A2(b_reg[4]),
	.B1(cycle_count[2]),
	.B2(b_reg[0]),
	.ZN(n_16), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3047__7482 (
	.A1(n_6),
	.A2(b_reg[7]),
	.B1(cycle_count[2]),
	.B2(b_reg[3]),
	.ZN(n_15), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g3048 (
	.I(n_13),
	.ZN(n_14), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g3049 (
	.I(n_12),
	.ZN(n_11), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3050__4733 (
	.A1(cycle_count[0]),
	.A2(cycle_count[1]),
	.ZN(n_13), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3052__6161 (
	.A1(cycle_count[1]),
	.A2(cycle_count[0]),
	.ZN(n_12), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3054__9315 (
	.A1(cycle_count[1]),
	.A2(n_3),
	.ZN(n_10), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3055__9945 (
	.A1(div_counter[1]),
	.A2(n_4),
	.ZN(n_9), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g3056 (
	.I(start),
	.ZN(n_8), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g3074 (
	.I(precision[1]),
	.ZN(n_5), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d2 g3106 (
	.I(rst),
	.ZN(n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g2__2883 (
	.A1(cycle_count[1]),
	.A2(cycle_count[0]),
	.ZN(n_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g519__2346 (
	.A1(add_73_46_n_315),
	.A2(add_73_46_n_496),
	.B1(add_73_46_n_315),
	.B2(add_73_46_n_496),
	.ZN(n_106), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ad01d1 add_73_46_g520__1666 (
	.A(shifted_a[14]),
	.B(result[14]),
	.CI(add_73_46_n_317),
	.CO(add_73_46_n_315),
	.S(n_105), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g522__6417 (
	.A1(add_73_46_n_322),
	.A2(add_73_46_n_391),
	.B1(add_73_46_n_322),
	.B2(add_73_46_n_391),
	.ZN(n_104), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim21d1 add_73_46_g523__5477 (
	.A(add_73_46_n_447),
	.B1(add_73_46_n_327),
	.B2(add_73_46_n_435),
	.ZN(add_73_46_n_322), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g524__2398 (
	.A1(add_73_46_n_327),
	.A2(add_73_46_n_414),
	.B1(add_73_46_n_327),
	.B2(add_73_46_n_414),
	.ZN(n_103), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g526__6260 (
	.A1(add_73_46_n_332),
	.A2(add_73_46_n_412),
	.B1(add_73_46_n_332),
	.B2(add_73_46_n_412),
	.ZN(n_102), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g528__8428 (
	.A1(n_132),
	.A2(add_73_46_n_413),
	.B1(n_132),
	.B2(add_73_46_n_413),
	.ZN(n_101), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g529__5526 (
	.A1(add_73_46_n_340),
	.A2(add_73_46_n_417),
	.B1(add_73_46_n_340),
	.B2(add_73_46_n_417),
	.ZN(n_100), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g531__3680 (
	.A1(add_73_46_n_345),
	.A2(add_73_46_n_441),
	.ZN(add_73_46_n_340), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g532__1617 (
	.A1(add_73_46_n_512),
	.A2(add_73_46_n_415),
	.B1(add_73_46_n_512),
	.B2(add_73_46_n_415),
	.ZN(n_99), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 add_73_46_g533__2802 (
	.A1(add_73_46_n_445),
	.A2(add_73_46_n_512),
	.ZN(add_73_46_n_345), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g535__1705 (
	.A1(add_73_46_n_352),
	.A2(add_73_46_n_416),
	.B1(add_73_46_n_352),
	.B2(add_73_46_n_416),
	.ZN(n_98), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g536__5122 (
	.A1(add_73_46_n_356),
	.A2(add_73_46_n_428),
	.ZN(add_73_46_n_352), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g537__8246 (
	.A1(n_133),
	.A2(add_73_46_n_394),
	.B1(n_133),
	.B2(add_73_46_n_394),
	.ZN(n_97), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 add_73_46_g538__7098 (
	.A1(add_73_46_n_452),
	.A2(n_133),
	.ZN(add_73_46_n_356), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g539__6131 (
	.A1(add_73_46_n_362),
	.A2(add_73_46_n_390),
	.B1(add_73_46_n_362),
	.B2(add_73_46_n_390),
	.ZN(n_96), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd03d1 add_73_46_g541__5115 (
	.A1(add_73_46_n_368),
	.A2(add_73_46_n_433),
	.A3(add_73_46_n_439),
	.ZN(add_73_46_n_361), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim21d1 add_73_46_g542__7482 (
	.A(add_73_46_n_457),
	.B1(add_73_46_n_368),
	.B2(add_73_46_n_433),
	.ZN(add_73_46_n_362), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g543__4733 (
	.A1(add_73_46_n_368),
	.A2(add_73_46_n_411),
	.B1(add_73_46_n_368),
	.B2(add_73_46_n_411),
	.ZN(n_95), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aor22d1 add_73_46_g544__6161 (
	.A1(add_73_46_n_373),
	.A2(add_73_46_n_430),
	.B1(shifted_a[3]),
	.B2(result[3]),
	.Z(add_73_46_n_368), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g545__9315 (
	.A1(add_73_46_n_373),
	.A2(add_73_46_n_393),
	.B1(add_73_46_n_373),
	.B2(add_73_46_n_393),
	.ZN(n_94), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g546__9945 (
	.A1(add_73_46_n_377),
	.A2(add_73_46_n_431),
	.ZN(add_73_46_n_373), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g547__2883 (
	.A1(n_134),
	.A2(add_73_46_n_389),
	.B1(n_134),
	.B2(add_73_46_n_389),
	.ZN(n_93), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 add_73_46_g548__2346 (
	.A1(add_73_46_n_434),
	.A2(n_134),
	.ZN(add_73_46_n_377), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 add_73_46_g550__7410 (
	.A1(add_73_46_n_392),
	.A2(add_73_46_n_384),
	.B1(add_73_46_n_392),
	.B2(add_73_46_n_384),
	.ZN(n_92), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 add_73_46_g556__5107 (
	.A1(add_73_46_n_434),
	.A2(add_73_46_n_431),
	.ZN(add_73_46_n_389), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g557__6260 (
	.A1(add_73_46_n_439),
	.A2(add_73_46_n_454),
	.ZN(add_73_46_n_390), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g558__4319 (
	.A1(add_73_46_n_453),
	.A2(add_73_46_n_437),
	.ZN(add_73_46_n_391), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an02d1 add_73_46_g559__8428 (
	.A1(add_73_46_n_513),
	.A2(add_73_46_n_436),
	.Z(add_73_46_n_392), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim21d1 add_73_46_g560__5526 (
	.A(add_73_46_n_430),
	.B1(shifted_a[3]),
	.B2(result[3]),
	.ZN(add_73_46_n_393), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 add_73_46_g561__6783 (
	.A1(add_73_46_n_452),
	.A2(add_73_46_n_428),
	.ZN(add_73_46_n_394), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim21d1 add_73_46_g562__3680 (
	.A(add_73_46_n_458),
	.B1(result[0]),
	.B2(shifted_a[0]),
	.ZN(n_91), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g563__1617 (
	.A1(add_73_46_n_433),
	.A2(add_73_46_n_457),
	.ZN(add_73_46_n_411), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g564__2802 (
	.A1(add_73_46_n_451),
	.A2(add_73_46_n_446),
	.ZN(add_73_46_n_412), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g565__1705 (
	.A1(add_73_46_n_456),
	.A2(add_73_46_n_455),
	.ZN(add_73_46_n_413), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g566__5122 (
	.A1(add_73_46_n_435),
	.A2(add_73_46_n_447),
	.ZN(add_73_46_n_414), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 add_73_46_g567__8246 (
	.A1(add_73_46_n_445),
	.A2(add_73_46_n_441),
	.ZN(add_73_46_n_415), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g568__7098 (
	.A1(add_73_46_n_429),
	.A2(add_73_46_n_449),
	.ZN(add_73_46_n_416), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 add_73_46_g569__6131 (
	.A1(add_73_46_n_438),
	.A2(add_73_46_n_450),
	.ZN(add_73_46_n_417), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 add_73_46_g570 (
	.I(add_73_46_n_440),
	.ZN(add_73_46_n_439), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g571__1881 (
	.A1(result[6]),
	.A2(shifted_a[6]),
	.ZN(add_73_46_n_428), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d0 add_73_46_g572__5115 (
	.A1(shifted_a[7]),
	.A2(result[7]),
	.Z(add_73_46_n_429), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d0 add_73_46_g573__7482 (
	.A1(shifted_a[3]),
	.A2(result[3]),
	.Z(add_73_46_n_430), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g574__4733 (
	.A1(result[2]),
	.A2(shifted_a[2]),
	.ZN(add_73_46_n_431), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 add_73_46_g576__6161 (
	.A1(shifted_a[4]),
	.A2(result[4]),
	.Z(add_73_46_n_433), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 add_73_46_g577__9315 (
	.A1(shifted_a[2]),
	.A2(result[2]),
	.ZN(add_73_46_n_434), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d0 add_73_46_g578__9945 (
	.A1(shifted_a[12]),
	.A2(result[12]),
	.Z(add_73_46_n_435), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g579__2883 (
	.A1(result[1]),
	.A2(shifted_a[1]),
	.ZN(add_73_46_n_436), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g580__2346 (
	.A1(result[13]),
	.A2(shifted_a[13]),
	.ZN(add_73_46_n_437), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 add_73_46_g581__1666 (
	.A1(shifted_a[9]),
	.A2(result[9]),
	.ZN(add_73_46_n_438), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 add_73_46_g582__7410 (
	.A1(shifted_a[5]),
	.A2(result[5]),
	.ZN(add_73_46_n_440), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g583__6417 (
	.A1(result[8]),
	.A2(shifted_a[8]),
	.ZN(add_73_46_n_441), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 add_73_46_g586__5477 (
	.A1(shifted_a[8]),
	.A2(result[8]),
	.ZN(add_73_46_n_445), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g587__2398 (
	.A1(result[11]),
	.A2(shifted_a[11]),
	.ZN(add_73_46_n_446), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g588__5107 (
	.A1(result[12]),
	.A2(shifted_a[12]),
	.ZN(add_73_46_n_447), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g589__6260 (
	.A1(result[7]),
	.A2(shifted_a[7]),
	.ZN(add_73_46_n_449), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g590__4319 (
	.A1(result[9]),
	.A2(shifted_a[9]),
	.ZN(add_73_46_n_450), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 add_73_46_g591__8428 (
	.A1(shifted_a[11]),
	.A2(result[11]),
	.Z(add_73_46_n_451), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 add_73_46_g592__5526 (
	.A1(shifted_a[6]),
	.A2(result[6]),
	.ZN(add_73_46_n_452), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d0 add_73_46_g593__6783 (
	.A1(shifted_a[13]),
	.A2(result[13]),
	.Z(add_73_46_n_453), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g594__3680 (
	.A1(result[5]),
	.A2(shifted_a[5]),
	.ZN(add_73_46_n_454), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g595__1617 (
	.A1(result[10]),
	.A2(shifted_a[10]),
	.ZN(add_73_46_n_455), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 add_73_46_g596__2802 (
	.A1(shifted_a[10]),
	.A2(result[10]),
	.Z(add_73_46_n_456), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g597__1705 (
	.A1(result[4]),
	.A2(shifted_a[4]),
	.ZN(add_73_46_n_457), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 add_73_46_g598__5122 (
	.A1(result[0]),
	.A2(shifted_a[0]),
	.ZN(add_73_46_n_384), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 add_73_46_g601__7098 (
	.A1(shifted_a[1]),
	.A2(result[1]),
	.Z(add_73_46_n_513), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aon211d1 g2 (
	.A(add_73_46_n_450),
	.B(add_73_46_n_438),
	.C1(add_73_46_n_441),
	.C2(add_73_46_n_345),
	.ZN(n_132), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrb1 \cycle_count_reg[3]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_59),
	.Q(cycle_count[3]),
	.QN(n_7), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrb1 \cycle_count_reg[2]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_56),
	.Q(cycle_count[2]),
	.QN(n_6), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrb4 \div_counter_reg[0]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(FE_PHN18_div_counter_0),
	.Q(n_4),
	.QN(div_counter[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrb1 \cycle_count_reg[0]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_55),
	.Q(cycle_count[0]),
	.QN(n_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrb1 state_reg (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_57),
	.Q(state),
	.QN(n_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrb2 \result_reg[15]  (
	.CDN(FE_PHN1_n_1),
	.CP(clk_in),
	.D(n_87),
	.Q(result[15]),
	.QN(add_73_46_n_496), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

